apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/JasonPowr/fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fbc-v4-15
    appstudio.openshift.io/component: fbc-v4-15
    pipelines.appstudio.openshift.io/type: build
  name: fbc-v4-15-on-push
  namespace: japower-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/japower-tenant/fbc-v4-15:{{revision}}
  - name: path-context
    value: v4.15
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: v4.15/catalog.Dockerfile
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/fbc-builder.yaml'
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
